
services:
  db:
    image: postgres:11.5-alpine
    ports:
      - 35432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  client:
    image: node:12.5-alpine
    command: yarn start
    ports:
      - 33000:33000
    volumes:
      - ./client:/client
      - /client/node_modules

  e2e:
    image: cypress/included:4.12.1
    command: echo 'Not run in dev'
    entrypoint: ""
    environment:
      CYPRESS_BASE_URL: http://client:33000
    volumes:
      - ./e2e:/e2e
    working_dir: /e2e
