<script>
  import TrailedText from "$lib/components/TrailedText.svelte";
  import TrailStore from "$lib/components/Trail/store";
  import Typewriter from "svelte-typewriter";
  import { onMount } from "svelte";
  import { spring } from "svelte/motion";
  import { browser } from "$app/environment";
  import LandingSection from "$lib/components/LandingSection.svelte";
  import { HEADING_CLASSES, SUBHEADING_CLASSES } from "$lib/constants";
  import { inview } from "svelte-inview";

  let scrollY;
  let expandsAreInView;
  onMount(() => {
    TrailStore.play();
  });

  let ySpring = spring(0);

  let height, width;

  ySpring.subscribe((y) => {
    if (browser) {
      window.scrollTo(0, y);
    }
  });
</script>

<svelte:window bind:scrollY bind:innerHeight={height} bind:innerWidth={width} />

<LandingSection class="justify-center">
  <div class="align-center relative my-12 md:max-w-xl lg:max-w-3xl lg:p-5">
    <h1
      class="{HEADING_CLASSES} min-h-[3em] w-full text-left font-thin"
      aria-label="the future of engineering is human."
    >
      <TrailedText />
    </h1>
  </div>
</LandingSection>
<LandingSection class="mx-auto justify-around">
  <div class="align-center relative my-12 h-full p-2 lg:p-5" use:inview>
    <h1 class="{HEADING_CLASSES} mb-4 text-center font-thin">
      i'm <span class="font-bold">diana.</span>
    </h1>
    <h2 class="{SUBHEADING_CLASSES} text-center font-thin">
      <a href="/gallery/code" class="w-inherit">coder.</a><a href="/gallery">creator.</a><a
        href="/blog">commnuicator.</a
      >
    </h2>
  </div>
  <img
    src="/images/diana-and-rafiki.jpg"
    class="mx-auto max-w-xs rounded-full border-2 border-white"
    alt="Diana and her dog "
  />
  <div
    class="relative my-[100px] p-2 text-right text-lg md:text-xl lg:p-5 lg:text-2xl"
    use:inview={{ threshold: 1, rootMargin: "100px" }}
    on:enter={() => {
      console.log("entering");
      expandsAreInView = true;
    }}
    on:leave={() => {
      console.log("exiting");
      expandsAreInView = false;
    }}
  >
    <div
      class="m-auto my-5 max-w-lg flex-col overflow-hidden p-5 text-left font-monospace font-thin"
      class:exit={!expandsAreInView}
      class:enter={expandsAreInView}
    >
      <div class="relative flex h-full min-h-[200px] w-full rounded-md bg-neutral-800 p-2 shadow">
        <div id="buttons" class="absolute top-3 left-3 flex w-full flex-row justify-start">
          <div class="mr-2 h-3 w-3 rounded-full bg-red-500" />
          <div class="mr-2 h-3 w-3 rounded-full bg-yellow-500" />
          <div class="mr-2 h-3 w-3 rounded-full bg-green-500" />
        </div>
        <div class="w-full pb-3 pt-8 text-xl">
          {#if expandsAreInView}
            <p>
              <Typewriter mode="cascade">
                Software Engineer, <!-- intentional line break for typewriter timing-->
                Humane Technologist. <!-- intentional line break for typewriter timing-->
                Digital Policy Buff, <!-- intentional line break for typewriter timing-->
                User Rights Enthusiast. <!-- intentional line break for typewriter timing-->
                Former Scientist, <!-- intentional line break for typewriter timing-->
                Forever Experimenting. <!-- intentional line break for typewriter timing-->
                <!-- intentional line break for typewriter timing-->
              </Typewriter>
            </p>
          {/if}
        </div>
      </div>
    </div>
  </div>
</LandingSection>

<style>
  /* ----------------------------------------------
 * Generated by Animista on 2022-11-14 21:3:36
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation fade-out-top
 * ----------------------------------------
 */
  @-webkit-keyframes fade-out-top {
    0% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
  }
  @keyframes fade-out-top {
    0% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2022-11-14 21:4:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation fade-in-top
 * ----------------------------------------
 */
  @-webkit-keyframes fade-in-top {
    0% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }
  @keyframes fade-in-top {
    0% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }

  .enter {
    /* .fade-in-top  */
    -webkit-animation: fade-in-top 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
    animation: fade-in-top 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  }

  .exit {
    /* .fade-out-top  */
    -webkit-animation: fade-out-top 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    animation: fade-out-top 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  }
</style>
