<script>
  import TrailedText from "$lib/components/TrailedText.svelte";
  import TrailStore from "$lib/components/Trail/store";
  import { onMount } from "svelte";
  import { spring } from "svelte/motion";
  import { browser } from "$app/environment";
  import LandingSection from "$lib/components/LandingSection.svelte";
  import { HEADING_CLASSES, SUBHEADING_CLASSES } from "$lib/constants";
  import Expandable from "$lib/components/Expandable.svelte";
  import { inview } from "svelte-inview";

  let scrollY;
  let expandsAreInView;
  onMount(() => {
    TrailStore.play();
  });

  let ySpring = spring(0);

  let height, width;

  ySpring.subscribe((y) => {
    if (browser) {
      window.scrollTo(0, y);
    }
  });
</script>

<svelte:window bind:scrollY bind:innerHeight={height} bind:innerWidth={width} />

<LandingSection class="justify-center">
  <div class="align-center relative my-12 md:max-w-xl lg:max-w-3xl lg:p-5">
    <h1
      class="{HEADING_CLASSES} min-h-[3em] w-full text-left font-thin"
      aria-label="the future of engineering is human."
    >
      <TrailedText />
    </h1>
  </div>
</LandingSection>
<LandingSection class="mx-auto justify-around">
  <div class="align-center relative my-12 h-full p-2 lg:p-5">
    <h1 class="{HEADING_CLASSES} mb-4 text-center font-thin">
      i'm <span class="font-bold">diana.</span>
    </h1>
    <h2 class="{SUBHEADING_CLASSES} text-center font-thin">
      <a href="/gallery/code" class="w-inherit">coder.</a><a href="/gallery">creator.</a><a
        href="/blog">commnuicator.</a
      >
    </h2>
  </div>
  <img
    src="/images/diana-and-rafiki.jpg"
    class="mx-auto max-w-xs rounded-full border-2 border-white"
    alt="Diana and her dog "
  />
  <!-- </LandingSection>
<LandingSection> -->

  <div
    class="relative my-[100px] p-2 text-right text-lg md:text-xl lg:p-5 lg:text-2xl"
    use:inview={{ threshold: 1, rootMargin: "100px" }}
    on:enter={(evt) => {
      console.log("entering");
      expandsAreInView = true;
    }}
    on:leave={(evt) => {
      console.log("exiting");
      expandsAreInView = false;
    }}
  >
    <div
      class="m-auto flex flex-col"
      style="width: max-content;"
      class:exit={!expandsAreInView}
      class:enter={expandsAreInView}
    >
      <Expandable title="Full Stack Software Engineer">
        <p class="my-5 font-thin">Ea sunt magna id nostrud sint velit id ad in.</p>
      </Expandable>
      <Expandable title="Digital Policy Buff, User Advocate " />
      <Expandable title="Former Scientist, Forever Experimenting" />
    </div>
  </div>
</LandingSection>

<style>
  /* ----------------------------------------------
 * Generated by Animista on 2022-11-14 21:3:36
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation fade-out-top
 * ----------------------------------------
 */
  @-webkit-keyframes fade-out-top {
    0% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
  }
  @keyframes fade-out-top {
    0% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2022-11-14 21:4:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation fade-in-top
 * ----------------------------------------
 */
  @-webkit-keyframes fade-in-top {
    0% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }
  @keyframes fade-in-top {
    0% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }

  .enter {
    /* .fade-in-top  */
    -webkit-animation: fade-in-top 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
    animation: fade-in-top 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  }

  .exit {
    /* .fade-out-top  */
    -webkit-animation: fade-out-top 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    animation: fade-out-top 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  }
</style>
