<script>
  import ComputerScreen from "$lib/components/ComputerScreen.svelte";
  import Typewriter from "svelte-typewriter";
  import { onMount } from "svelte";
  import { spring } from "svelte/motion";
  import { browser } from "$app/environment";
  import LandingSection from "$lib/components/LandingSection.svelte";
  import { HEADING_CLASSES, SUBHEADING_CLASSES } from "$lib/constants";
  import { inview } from "svelte-inview";
  import { fade } from "svelte/transition";
  import Button from "$lib/components/Button.svelte";

  let scrollY;
  let landingIsInView;
  let firstTypewriterIsDone;
  let secondTypewriterIsDone;

  let ySpring = spring(0, {
    stiffness: 0.05,
    damping: 0.8
  });

  let height, width;

  ySpring.subscribe((y) => {
    if (browser) {
      window.scrollTo(0, y);
    }
  });

  function onDownClick() {
    const sections = document.querySelectorAll("section");
    const secondSection = sections[1];
    ySpring.set(secondSection.offsetTop);
  }

  let mounted = false;
  onMount(() => {
    mounted = true;
    return () => {
      mounted = false
    }
  })

</script>

<svelte:window bind:scrollY bind:innerHeight={height} bind:innerWidth={width} />

<LandingSection class="justify-center font-monospace">
  <div
    class="relative bg-darkest-gray lg:min-w-md m-auto  w-full max-w-sm md:max-w-lg flex flex-col justify-between text-left font-thin "
    >
    <div id="framebar" class="rounded-tr-lg rounded-tl-lg bg-dark-gray absolute -top-10 w-full h-10 left-0">
    <span class="text-gray rounded-full px-2 py-1 cursor-none">x</span>  
    </div>
    <div class="w-full min-h-[200px] flex flex-col justify-between p-5">
    {#if mounted}
        <p class="text-3xl">
          <Typewriter on:done={() => (firstTypewriterIsDone = true)}>
            the future <!-- intentional line break for typewriter timing-->
            of <!-- intentional line break for typewriter timing-->
            engineering <!-- intentional line break for typewriter timing-->
            is <!-- intentional line break for typewriter timing-->
            human. <!-- intentional line break for typewriter timing-->
          </Typewriter>
        </p>
    
    <span class="text-3xl min-h-[1em] font-thin mt-5">
      {#if firstTypewriterIsDone}
      <Typewriter delay={800} on:done={() => (secondTypewriterIsDone = true)}>
      hi. <!-- intentional line break for typewriter timing-->
       <!-- intentional line break for typewriter timing-->
       <!-- intentional line break for typewriter timing-->
       <!-- intentional line break for typewriter timing-->
      i'm <!-- intentional line break for typewriter timing-->
      diana.</Typewriter>
      {/if}
    </span>
    {/if}
  </div>

  </div>
  <div class="flex justify-center">
    {#key secondTypewriterIsDone}
    <button
      class:invisible={!secondTypewriterIsDone}
      disabled={!secondTypewriterIsDone}
      on:click={onDownClick}
      in:fade
      class="z-10 bg-darkest-gray hover:border-gray hover:bg-darkest-gray w-fit rounded-full p-5 text-white hover:border"
    >
    <i class="las la-angle-down" aria-hidden="true" />
    <span class="sr-only">down</span>
    </button>
    {/key}
  </div>
</LandingSection>
<LandingSection class="mx-auto justify-around">
  <div class="align-center relative my-12 h-full p-2 lg:p-5">
    <h1 class="{HEADING_CLASSES} mb-4 text-center font-bold">Diana M. Steakley-Freeman</h1>
    <p class="{SUBHEADING_CLASSES} text-center font-thin">coder. creator. communicator.</p>
  </div>
  <div class="gap-4 md:flex">
    <img
      src="/images/diana-and-rafiki.jpg"
      class="mx-auto max-w-xs rounded-full border-2 border-white"
      alt=""
    />
    <div class="flex w-full flex-col justify-between p-5 md:w-1/2">
      <p class="m-auto my-3">
        Full Stack Software Engineer. 10+ years of website and application development in academic,
        medical, nonprofit, and start-up environments.
      </p>
      <p class="m-auto my-3">
        Digital Policy Buff, User Rights Enthusiast, Former Scientist, Forever Experimenting.
        Enthusiastic nerd.
      </p>
      <Button class="bg-darkest-gray my-auto w-fit p-5">More about Diana</Button>
    </div>
  </div>
</LandingSection>
<LandingSection class="mx-auto justify-around">
  <h2>Let's Connect!</h2>
</LandingSection>

<style>
  /* ----------------------------------------------
 * Generated by Animista on 2022-11-14 21:3:36
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation fade-out-top
 * ----------------------------------------
 */
  @-webkit-keyframes fade-out-top {
    0% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
  }
  @keyframes fade-out-top {
    0% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2022-11-14 21:4:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation fade-in-top
 * ----------------------------------------
 */
  @-webkit-keyframes fade-in-top {
    0% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }
  @keyframes fade-in-top {
    0% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }

  .enter {
    /* .fade-in-top  */
    -webkit-animation: fade-in-top 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
    animation: fade-in-top 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  }

  .exit {
    /* .fade-out-top  */
    -webkit-animation: fade-out-top 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    animation: fade-out-top 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  }
</style>
