version: 2
commands:
  static-build:
    description: "Build Static Site"
    steps:
      - run:
          name: Do Static Build
          command: yarn build


jobs:
  build:
    docker:
      - image: node:10
    working_directory: ~/web
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ checksum "yarn.lock" }}
            - node-deps-
      - run:
          name: Install Dependencies
          command: yarn install --loglevel=error
      - save_cache:
          key: node-deps-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build Static
          command: yarn build

  test:
    parallelism: 2
    docker:
      - image: node:10
    working_directory: ~/test
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ checksum "yarn.lock" }}
            - node-deps-
      - run:
          name: Install Dependencies
          command: yarn install --loglevel=error
      - run:
          name: Run Tests
          command: yarn test

  test-e2e:
    parallelism: 2
    docker:
      - image: cypress/base:10
    working_directory: ~/web/builds
    environment:
          ## this enables colors in the output
          TERM: xterm
          CIRCLE_WORKING_DIRECTORY: ~/web
    steps:
      - checkout
      - restore_cache:
          keys:
            - public-dir-{{ .Branch }}
            - public-dir-
      - run:
          name: Install Dependencies
          command: yarn install --loglevel=error
      - save_cache:
          key: public-dir-{{ .Branch }}
          paths:
            - ./public
      - run:
          name: Run End To End test
          command: test:e2e:ci

  deploy:
    docker:
      - image: circleci/node:10
    environment:
      NETLIFY_SITE_ID: 7b5f4c1a-c979-4652-aacf-05076bfa2989
      NETLIFY_ACCESS_TOKEN: a6061c1d46a3356fb1307d13a7b49e84716936ea891f1e0398638991c2d6cd53
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Netlify Deploy
          command: $(yarn bin)/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=public

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - test-e2e
      - deploy:
          requires:
            - test
            - test-e2e
