media_folder: "static/images" # Media files will be stored in the repo under images/uploads
public_folder: "/images" # Media files will be stored in the repo under images/uploads

backend:
  name: git-gateway

# UNCOMMENT THIS during local development
# local_backend: true
# url: http://localhost:8081/api/v1

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    label_singular: "Post" # Used in the UI
    folder: "src/routes/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "resources" # Used in routes, e.g., /admin/collections/blog
    label: "Resources" # Used in the UI
    label_singular: "Resource" # Used in the UI
    folder: "src/routes/resources" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "code" # Used in routes, e.g., /admin/collections/blog
    label: "Code Projects" # Used in the UI
    label_singular: "Code Project" # Used in the UI
    folder: "src/routes/projects/code" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "science" # Used in routes, e.g., /admin/collections/blog
    label: "Science Projects" # Used in the UI
    label_singular: "Science Project" # Used in the UI
    folder: "src/routes/projects/science" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "art" # Used in routes, e.g., /admin/collections/blog
    label: "Art Projects" # Used in the UI
    label_singular: "Art Project" # Used in the UI
    folder: "src/routes/projects/art" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "design" # Used in routes, e.g., /admin/collections/blog
    label: "Design Projects" # Used in the UI
    label_singular: "Design Project" # Used in the UI
    folder: "src/routes/projects/design" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Page Slug", name: "slug", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true }
      - { label: "Body", name: "body", widget: "markdown" }

  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/routes/_metadata.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Slug, name: slug, widget: string }
          - { label: "Relative Path", name: relativePath, widget: string }
          - { label: "Featured Image", name: image, widget: "image" }
          - { label: "Draft", name: "draft", widget: "boolean" }
          - {
              label: "Navigation Display Text",
              name: navigationText,
              widget: string
            }

      - label: "Blog Page"
        name: "blog"
        file: "src/routes/blog/_metadata.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Slug, name: slug, widget: string }
          - { label: "Relative Path", name: relativePath, widget: string }
          - { label: "Featured Image", name: image, widget: "image" }
          - {
              label: "Navigation Display Text",
              name: navigationText,
              widget: string
            }

      - label: "Resources Page"
        name: "resources"
        file: "src/routes/resources/_metadata.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Slug, name: slug, widget: string }
          - { label: "Relative Path", name: relativePath, widget: string }
          - { label: "Featured Image", name: image, widget: "image" }
          - {
              label: "Navigation Display Text",
              name: navigationText,
              widget: string
            }

      - label: "Projects Page"
        name: "projects"
        file: "src/routes/projects/_metadata.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Slug, name: slug, widget: string }
          - { label: "Relative Path", name: relativePath, widget: string }
          - { label: "Featured Image", name: image, widget: "image" }
          - { label: "Draft", name: "draft", widget: "boolean" }
          - {
              label: "Navigation Display Text",
              name: navigationText,
              widget: string
            }

      - label: "Art Projects Page"
        name: "art"
        file: "src/routes/projects/art/_metadata.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Slug, name: slug, widget: string }
          - { label: "Relative Path", name: relativePath, widget: string }
          - { label: "Featured Image", name: image, widget: "image" }
          - {
              label: "Navigation Display Text",
              name: navigationText,
              widget: string
            }

      - label: "Code Projects Page"
        name: "code"
        file: "src/routes/projects/code/_metadata.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Slug, name: slug, widget: string }
          - { label: "Relative Path", name: relativePath, widget: string }
          - { label: "Featured Image", name: image, widget: "image" }
          - {
              label: "Navigation Display Text",
              name: navigationText,
              widget: string
            }

      - label: "Design Projects Page"
        name: "design"
        file: "src/routes/projects/design/_metadata.json"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Slug, name: slug, widget: string }
          - { label: "Relative Path", name: relativePath, widget: string }
          - { label: "Featured Image", name: image, widget: "image" }
          - {
              label: "Navigation Display Text",
              name: navigationText,
              widget: string
            }
