/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useThree } from "@react-three/fiber";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/glb/MacBookPro_blend.glb");

  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[0.76, 0.73, -0.43]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.57, 0.03, 1.43]}
      >
        <mesh geometry={nodes.Cube004.geometry} material={materials.Outline} />
        <mesh geometry={nodes.Cube004_1.geometry} material={materials.Screen} />
        <mesh
          geometry={nodes.Cube004_2.geometry}
          material={materials.Emission}
        />
        <mesh geometry={nodes.Cube004_3.geometry} material={materials.Logo} />
        <mesh
          geometry={nodes.Cube004_4.geometry}
          material={nodes.Cube004_4.material}
        />
        <mesh geometry={nodes.Cube004_5.geometry} material={materials.Text} />
        <mesh geometry={nodes.Cube004_6.geometry} material={materials.Camera} />
        <mesh
          geometry={nodes.Cube004_7.geometry}
          material={materials.Camera1}
        />
        <mesh
          geometry={nodes.Cube004_8.geometry}
          material={materials.CameraGreen}
        />
      </group>
      <group position={[-1.07, 0.7, -1.86]} scale={[1.57, 0.03, 1.43]}>
        <mesh geometry={nodes.Cube005.geometry}>
          <meshStandardMaterial color="#2b2b2b" />
        </mesh>
        <mesh
          geometry={nodes.Cube005_1.geometry}
          material={nodes.Cube005_1.material}
        />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials.Second} />
        <mesh geometry={nodes.Cube005_3.geometry} material={materials.KeysMain}>
          <meshStandardMaterial color="black" />
        </mesh>
        <mesh
          geometry={nodes.Cube005_4.geometry}
          material={materials.KeysBottom}
        />
        <mesh
          geometry={nodes.Cube005_5.geometry}
          material={materials.TopLine}
        />
        <mesh
          geometry={nodes.Cube005_6.geometry}
          material={materials.DarkGrey}
        />
      </group>
      {/* <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        position={[0.03, 0.64, -0.03]}
        rotation={[-Math.PI, 1.07, -Math.PI]}
        scale={35.5}
      /> */}
    </group>
  );
}

useGLTF.preload("/MacBookPro_blend.glb");
