/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, Html } from "@react-three/drei";
import { a, useSpring, config } from "@react-spring/three";
import * as THREE from "three";

export default function Model({ props, open, children }) {
  const group = useRef();
  const screenGroup = useRef();
  const { nodes, materials } = useGLTF("/glb/MacBookPro_blend.glb");

  useEffect(() => {
    // Center the group on mount
    new THREE.Box3()
      .setFromObject(group.current)
      .getCenter(group.current.position)
      .multiplyScalar(-1);
  }, []);

  // useFrame((state) => {
  //   // Make the laptop float
  //   const t = state.clock.getElapsedTime();

  //   group.current.position.y = THREE.MathUtils.lerp(
  //     group.current.position.y,
  //     (-5 + Math.sin(t)) / 5,
  //     0.1
  //   );
  // });

  const { screenRotation } = useSpring({
    screenRotation: open ? Math.PI / 2 : 0,
    config: config.molasses,
  });
  return (
    <a.group ref={group} {...props} dispose={null}>
      {/* // Screen Group */}
      <a.group
        ref={screenGroup}
        position={[0.76, 0.73, -0.43]}
        rotation-x={screenRotation}
        rotation-y={0}
        rotation-z={0}
        scale={[1.57, 0.03, 1.43]}
      >
        <mesh
          // Front Laptop Shell
          geometry={nodes.Cube004.geometry}
          material={materials.Outline}
        />
        <mesh
          // screen
          geometry={nodes.Cube004_1.geometry}
          // material={materials.Screen}
        />
        <mesh geometry={nodes.Cube004_6.geometry} material={materials.Camera} />

        <mesh
          // apple logo
          geometry={nodes.Cube004_3.geometry}
          material={materials.Logo}
        />
        <mesh
          // Back Laptop Shell
          geometry={nodes.Cube004_4.geometry}
          material={nodes.Cube004_4.material}
        />
        <mesh
          geometry={nodes.Cube004_7.geometry}
          material={materials.Camera1}
        />
        <mesh
          // Camera, ring
          // Add a green mesh to make this look like its running
          geometry={nodes.Cube004_8.geometry}
          material={materials.CameraGreen}
        />

        {children}
      </a.group>
      <a.group position={[-1.07, 0.7, -1.86]} scale={[1.57, 0.03, 1.43]}>
        <mesh geometry={nodes.Cube005.geometry}>
          <meshStandardMaterial color="#2b2b2b" />
        </mesh>
        <mesh
          geometry={nodes.Cube005_1.geometry}
          material={nodes.Cube005_1.material}
        />
        <mesh geometry={nodes.Cube005_2.geometry} material={materials.Second} />
        <mesh geometry={nodes.Cube005_3.geometry} material={materials.KeysMain}>
          <meshStandardMaterial color="black" />
        </mesh>
        <mesh
          geometry={nodes.Cube005_4.geometry}
          material={materials.KeysBottom}
        />
        <mesh
          geometry={nodes.Cube005_5.geometry}
          material={materials.TopLine}
        />
        <mesh
          geometry={nodes.Cube005_6.geometry}
          material={materials.DarkGrey}
        />
      </a.group>
    </a.group>
  );
}

useGLTF.preload("/MacBookPro_blend.glb");
