<script>
  import Typewriter from "svelte-typewriter";
  import { fade } from "svelte/transition";

  let scrollY;

  let introTimeoutComplete = false;
  let shouldShake = false;
  let firstTypewriterIsDone = false;
  let secondTypewriterIsDone = false;
</script>

<svelte:window bind:scrollY />

<div
  class="lg:min-w-md relative m-auto flex w-full  flex-col justify-between text-left  font-thin md:max-w-lg ">
  <div
    id="framebar"
    class="absolute -top-10 left-0 h-10 w-full rounded-tr-lg rounded-tl-lg bg-dark-gray">
    <span class="cursor-none rounded-full px-2 py-1 text-light-gray">x</span>
  </div>
  <div
    class="flex min-h-[250px] w-full flex-col  justify-between bg-darkest-gray p-5 ">
    <p class="text-3xl">
      <Typewriter on:done={() => (firstTypewriterIsDone = true)}>
        the future <!-- intentional line break for typewriter timing-->
        of <!-- intentional line break for typewriter timing-->
        engineering <!-- intentional line break for typewriter timing-->
        is <!-- intentional line break for typewriter timing-->
        human. <!-- intentional line break for typewriter timing-->
      </Typewriter>
    </p>

    <span class="mt-5 min-h-[1em] text-3xl font-thin">
      {#if firstTypewriterIsDone}
        <Typewriter
          delay={800}
          on:done={() => {
            secondTypewriterIsDone = true;
            setTimeout(() => {
              introTimeoutComplete = true;
            }, 1000);
          }}>
          hi. <!-- intentional line break for typewriter timing-->
          <!-- intentional line break for typewriter timing-->
          i'm <!-- intentional line break for typewriter timing-->
          diana.</Typewriter>
      {/if}
    </span>
  </div>
</div>
<div
  class="absolute bottom-20 left-0 w-full flex-col justify-end text-center align-middle">
  <!-- {#if secondTypewriterIsDone && !hasScrolled} -->
  <button
    transition:fade
    class=" text-dark-gray"
    class:shake-bottom={shouldShake}>scroll down</button>
  <!-- {/if} -->
</div>

<style>
  .shake-bottom {
    -webkit-animation: shake-bottom 0.8s cubic-bezier(0.455, 0.03, 0.515, 0.955)
      both;
    animation: shake-bottom 0.8s cubic-bezier(0.455, 0.03, 0.515, 0.955) both;
  }
  /* ----------------------------------------------
   * Generated by Animista on 2022-12-18 13:7:45
   * Licensed under FreeBSD License.
   * See http://animista.net/license for more info. 
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */

  /**
          "darkest-gray": "#181818",
          "dark-gray": "#222222",
          "gray": "#474747",
          "light-gray": "#808080",
          "lightest-gray": "#808080"
   * ----------------------------------------
   * animation shake-bottom
   * ----------------------------------------
   */
  @-webkit-keyframes shake-bottom {
    0%,
    100% {
      color: #222222;
      -webkit-transform: rotate(0deg);
      transform: rotate(0deg);
      -webkit-transform-origin: 50% 100%;
      transform-origin: 50% 100%;
    }
    10% {
      color: #808080;
      -webkit-transform: rotate(2deg);
      transform: rotate(2deg);
    }
    20%,
    40%,
    60% {
      color: #808080;
      -webkit-transform: rotate(-4deg);
      transform: rotate(-4deg);
    }
    30%,
    50%,
    70% {
      color: #808080;
      -webkit-transform: rotate(4deg);
      transform: rotate(4deg);
    }
    80% {
      color: #808080;
      -webkit-transform: rotate(-2deg);
      transform: rotate(-2deg);
    }
    90% {
      color: #808080;
      -webkit-transform: rotate(2deg);
      transform: rotate(2deg);
    }
  }
  @keyframes shake-bottom {
    0%,
    100% {
      color: #222222;
      -webkit-transform: rotate(0deg);
      transform: rotate(0deg);
      -webkit-transform-origin: 50% 100%;
      transform-origin: 50% 100%;
    }
    10% {
      color: #808080;
      -webkit-transform: rotate(2deg);
      transform: rotate(2deg);
    }
    20%,
    40%,
    60% {
      color: #808080;
      -webkit-transform: rotate(-4deg);
      transform: rotate(-4deg);
    }
    30%,
    50%,
    70% {
      color: #808080;
      -webkit-transform: rotate(4deg);
      transform: rotate(4deg);
    }
    80% {
      color: #808080;
      -webkit-transform: rotate(-2deg);
      transform: rotate(-2deg);
    }
    90% {
      color: #808080;
      -webkit-transform: rotate(2deg);
      transform: rotate(2deg);
    }
  }
</style>
