<script>
  import { inview } from "svelte-inview";
  import { topNavHeight } from "$stores/LayoutStore";

  let clazz;
  export { clazz as class };
  export let fadeInWhenVisible = true
  let sectionWrapper;
  let isVisible = false;
</script>

<section
  bind:this={sectionWrapper}
  use:inview={{ threshold: 0.25 }}
  on:change={(evt) => {
    const { inView } = evt.detail;
    isVisible = inView;
  }}
  class="my-auto flex w-full flex-col {clazz} {!isVisible && 'overflow-hidden'}"
  style="min-height: calc(100vh - {$topNavHeight}px)"
>
  <div
    class="flex flex-grow flex-col justify-evenly {fadeInWhenVisible ? `${isVisible ? 'enter' : "exit"}` : ""}"
  >
    <slot />
  </div>
</section>

<style>

.enter {
    /* .fade-in-top  */
    -webkit-animation: fade-in-top 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
    animation: fade-in-top 0.6s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  }

  .exit {
    /* .fade-out-top  */
    -webkit-animation: fade-out-top 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    animation: fade-out-top 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  }
/* ----------------------------------------------
 * Generated by Animista on 2022-11-14 21:3:36
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation fade-out-top
 * ----------------------------------------
 */
  @-webkit-keyframes fade-out-top {
    0% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
  }
  @keyframes fade-out-top {
    0% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
    100% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
  }

  /* ----------------------------------------------
 * Generated by Animista on 2022-11-14 21:4:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation fade-in-top
 * ----------------------------------------
 */
  @-webkit-keyframes fade-in-top {
    0% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }
  @keyframes fade-in-top {
    0% {
      -webkit-transform: translateY(-50px);
      transform: translateY(-50px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateY(0);
      transform: translateY(0);
      opacity: 1;
    }
  }

</style>
