name: CI Workflow

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging, staging@next ]

jobs:
  build-and-test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Install dependencies
      run: yarn  --frozen-lockfile

    - name: Check Formatting
      run: yarn run test:format

    - name: Run Unit Tests
      run: yarn run test:unit

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}

