name: Build and Deploy Pull Request To Netlify
on:
  push:
    branches:
      - "main"
      - "staging"

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - name: Restore NPM Deps & Modules
        id: restore-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ./node_modules
          key: node-cache-${{ hashFiles('**/package-lock.json') }}

      - name: Do Clean-Install
        if: steps.restore-dependencies.outputs.cache-hit != 'true'
        run: npm ci

      - name: Cache Dependencies
        uses: actions/cache@v3
        if: steps.restore-dependencies.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.npm
            ./node_modules
          key: node-cache-${{ hashFiles('**/package-lock.json') }}

      - name: Build Application
        run: npm run build

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=public --prod
