name: Build and Test

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging, staging@next ]

jobs:
  test:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install --silent

    - name: Check Formatting
      run: yarn run test:format

    - name: Run Unit Tests
      run: yarn run test:unit

