name: CI Workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npmN
        key: ${{ runner.OS }}-node-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Install dependencies
      run: yarn  --frozen-lockfile

    - name: Check Formatting
      run: yarn run test:format

    - name: Run Unit Tests
      run: yarn run test:unit
