name: Staging CI/CD

on:
  push:
    branches: [staging, staging@next]

jobs:
  build-and-test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Dependencies
        run: yarn install --silent --frozen-lockfile

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Run Unit Tests
        run: yarn test

      - name: Build Static Site
        run: yarn build

      - name: Cypress E2E
        uses: cypress-io/github-action@v2
        with:
          headless: true
          install: false
          start: yarn serve
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_TOKEN }}
