name: Staging CI/CD

on:
  push:
    branches: [ staging, staging@next ]

jobs:
  test-and-build:
    name: "Unit Test and Build"
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Files
      uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Dependencies
      run: yarn install --silent --frozen-lockfile

    - name: Cache Node Modules
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Run Unit Tests
      run: yarn test

    - name: Build Static Site
      run: yarn build

    - name: Cache Static Build
      uses: actions/cache@v2
      with:
        path: |
          public
          .cache
        key: static-build-${{ github.sha }}-${{ github.run_number }}


  test-e2e:
    name: "Test E2E"
    runs-on: ubuntu-latest
    needs: test-and-build
    steps:

      - name: Checkout Files
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Restore Dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install --silent --frozen-lockfile

      - name: Restore Static Build
        uses: actions/cache@v2
        with:
          path: |
            public
            .cache
          key: static-build-${{ github.sha }}-${{ github.run_number }}

      - name: Cypress E2E
        run: yarn test-e2e




